arch:
  - amd64
  - ppc64le
  
arch:
  - amd64
  - ppc64le
sudo: required
dist: trusty

language: node_js
node_js:
  - '0.12'

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd swagger-ui/
  - npm i -g jshint
  - npm install
  - cd ../storage
  - gradle test --info
  - cd ../crawler
  - gradle test --info
